# Generated by Django 4.2.7 on 2023-12-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfileManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
