# Generated by Django 4.2.7 on 2023-12-03 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vms_app', '0002_vendorprofilemanager_alter_purchaseorder_issue_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorProfileManager',
        ),
    ]
